<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>TPMVault</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyMetadata Include="TPMVault.RepositoryRoot" Value="$(MSBuildProjectDirectory)" />
    <Compile Remove="tests/**/*.cs" />
    <PackageReference Include="Microsoft.TSS" Version="2.1.1" />
  </ItemGroup>

</Project>
